version: "3"
services:
  db:
    image: mysql:5.7
    ports: 
      - 3306:3306
  api:
    build: .
    depends_on: 
      - db
    tty: true
    ports: 
      - 3000:3000
    volumes:
      - .:/app
